// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/page/container.vue')['default']
    Nav: typeof import('./src/components/page/nav.vue')['default']
    Overlay: typeof import('./src/components/loading/overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('./src/components/skeleton/index.vue')['default']
    SvgIcon: typeof import('./src/components/svg-icon.vue')['default']
    VanOverlay: typeof import('vant/es')['Overlay']
    Vertical: typeof import('./src/components/scroll-ad/vertical.vue')['default']
  }
}
